src/main/java/com/vertonur/bean/Forum.java
package com.vertonur.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import com.vertonur.pojo.Category;

public class Forum {

	private Category category;
	private List<Topic> recentTopics;
	private List<Topic> hotTopics;

	public Forum() {
		category = new Category();
	}

	public Forum(Category category) {
		this.category = category;
	}

	public void addAdmins(Set<Admin> admins) {
		Iterator<Admin> iterator = admins.iterator();
		Set<com.vertonur.pojo.Admin> coreAdmins = new HashSet<com.vertonur.pojo.Admin>();
		while (iterator.hasNext()) {
			Admin admin = iterator.next();
			coreAdmins.add(admin.getCore());
		}
		category.addAdmins(coreAdmins);
	}

	public Set<Admin> getAdmins() {
		Set<com.vertonur.pojo.Admin> coreAdmins = category.getAdmins();
		Iterator<com.vertonur.pojo.Admin> iterator = coreAdmins.iterator();
		Set<Admin> admins = new HashSet<Admin>();
		while (iterator.hasNext()) {
			com.vertonur.pojo.Admin coreAdmin = iterator.next();
			Admin admin = new Admin(coreAdmin);
			admins.add(admin);
		}
		return admins;
	}

	public Category getCore() {
		return category;
	}

	public String getDescription() {
		return category.getDescription();
	}

	public Forumzone getForumzone() {
		return new Forumzone(category.getDepartment());
	}

	public int getId() {
		return category.getId();
	}

	public String getName() {
		return category.getName();
	}

	public ForumStatistician getStatistician() {
		return new ForumStatistician(category.getStatistician());
	}

	public boolean isHasNewTopic() {
		return category.isHasNewInfo();
	}

	public void removeAdmins() {
		category.removeAdmins();
	}

	public void setCreatedTime(Date date) {
		category.setCreatedTime(date);
	}

	public void setCreator(Admin admin) {
		category.setCreator(admin.getCore());
	}

	public void setDescription(String description) {
		category.setDescription(description);
	}

	public void setName(String name) {
		category.setName(name);
	}

	public void setStatistician(ForumStatistician forumStatistician) {
		category.setStatistician(forumStatistician.getCore());
	}

	public boolean isModerated() {
		return category.isModerated();
	}

	public void setModerated(boolean moderated) {
		category.setModerated(moderated);
	}

	public boolean isDeprecated() {
		return category.isDeprecated();
	}

	public void setDeprecated(boolean deprecated) {
		category.setDeprecated(deprecated);
	}

	public List<Topic> getRecentTopics() {
		return recentTopics;
	}

	public void setRecentTopics(List<Topic> recentTopics) {
		this.recentTopics = recentTopics;
	}

	public List<Topic> getHotTopics() {
		return hotTopics;
	}

	public void setHotTopics(List<Topic> hotTopics) {
		this.hotTopics = hotTopics;
	}

	public int getPriority() {
		return category.getPriority();
	}

	public void setPriority(int priority) {
		category.setPriority(priority);
	}
}

src/main/java/com/vertonur/bean/ForumStatistician.java
package com.vertonur.bean;

import com.vertonur.pojo.Info;
import com.vertonur.pojo.statistician.CategoryStatistician;

public class ForumStatistician {

	private CategoryStatistician statistician;

	public ForumStatistician() {
		statistician = new CategoryStatistician();
	}

	public ForumStatistician(CategoryStatistician statistician) {
		this.statistician = statistician;
	}

	public void increaseRspNum() {
		statistician.increaseCommentNum();
	}

	public CategoryStatistician getCore() {
		return statistician;
	}

	public Topic getLatestTopic() {
		Info info = statistician.getLatestInfo();
		if (info == null)
			return null;

		return new Topic(info);
	}

	public int getTopicNum() {
		return statistician.getInfoNum();
	}

	public void setLatestTopic(Topic topic) {
		statistician.setLatestInfo(topic.getCore());
	}

	public void increaseToModerateNum() {
		statistician.increaseToModerateNum();
	}

	public void decreaseToModerateNum() {
		statistician.decreaseToModerateNum();
	}

	public int getToModerateNum() {
		return statistician.getToModerateNum();
	}

	public int getResponseNum() {
		return statistician.getCommentNum();
	}
}

src/main/java/com/vertonur/bean/Info.java
package com.vertonur.bean;

import java.util.Date;
import java.util.List;

import com.vertonur.pojo.AbstractInfo;
import com.vertonur.pojo.Attachment;
import com.vertonur.pojo.State;

public abstract class Info {

	public List<Attachment> getAttachments() {
		return getCore().getAttachments();
	}

	public User getAuthor() {
		return new User(getCore().getAuthor());
	}

	public String getContent() {
		return getCore().getContent();
	}

	public abstract AbstractInfo getCore();

	public Date getCreatedTime() {
		return getCore().getCreatedTime();
	}

	public int getId() {
		return getCore().getId();
	}

	public String getSubject() {
		return getCore().getSubject();
	}

	public void setAuthor(User theCurrentUser) {
		getCore().setAuthor(theCurrentUser.getCore());
	}

	public void setContent(String content) {
		getCore().setContent(content);
	}

	public void setCreatedTime(Date date) {
		getCore().setCreatedTime(date);
	}

	public void setSubject(String title) {
		getCore().setSubject(title);
	}

	public State getState() {
		return getCore().getState();
	}

	public void setState(State state) {
		getCore().setState(state);
	}
}

src/main/java/com/vertonur/bean/Topic.java
package com.vertonur.bean;

import com.vertonur.pojo.Info.InfoType;

public class Topic extends Info {

	private com.vertonur.pojo.Info info;

	public Topic() {
		info = new com.vertonur.pojo.Info();
	}

	public Topic(com.vertonur.pojo.Info info) {
		this.info = info;
	}

	@Override
	public com.vertonur.pojo.Info getCore() {
		return info;
	}

	public Forum getForum() {
		return new Forum(info.getCategory());
	}

	public TopicStatistician getStatistician() {
		return new TopicStatistician(info.getStatistician());
	}

	public boolean isNewToUser() {
		return info.isNewToUser();
	}

	public boolean isReadToUser() {
		return info.isReadToUser();
	}

	public void setNewToUser(boolean newToUser) {
		info.setNewToUser(newToUser);
	}

	public void setReadToUser(boolean readToUser) {
		info.setReadToUser(readToUser);
	}

	public void setStatistician(TopicStatistician statistician) {
		info.setStatistician(statistician.getCore());
	}

	public boolean isModerated() {
		return info.isModerated();
	}

	public void setForum(Forum forum) {
		info.setCategory(forum.getCore());
	}

	public InfoType getInfoType() {
		return info.getInfoType();
	}

	public void setInfoType(InfoType infoType) {
		info.setInfoType(infoType);
	}

	public boolean isLocked() {
		return info.isLocked();
	}
	
	public boolean isHot() {
		return info.isHot();
	}
}

src/main/java/com/vertonur/bean/TopicStatistician.java
package com.vertonur.bean;

import com.vertonur.pojo.Comment;
import com.vertonur.pojo.statistician.InfoStatistician;

public class TopicStatistician {

	private InfoStatistician statistician;

	public TopicStatistician() {
		this.statistician = new InfoStatistician();
	}

	public TopicStatistician(InfoStatistician statistician) {
		this.statistician = statistician;
	}

	public void addClickThroughRate() {
		statistician.addClickThroughRate();
	}

	public int getClickThroughRate() {
		return statistician.getClickThroughRate();
	}

	public InfoStatistician getCore() {
		return statistician;
	}

	public Response getLatestResponse() {
		Comment comment = statistician.getLatestComment();
		if (comment == null)
			return null;
		return new Response(comment);
	}

	public int getResponseNum() {
		return statistician.getCommentNum();
	}

	public void setLatestOne(boolean isLatestOne) {
		statistician.setLatestOne(isLatestOne);
	}

	public void setLatestResponse(Response latestResponse) {
		statistician.setLatestComment(latestResponse.getCore());
	}
	
	public void increaseToModerateNum() {
		statistician.increaseToModerateNum();
	}
}

src/main/java/com/vertonur/admin/action/user/LockUserAction.java
package com.vertonur.admin.action.user;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vertonur.admin.form.UserAdminForm;
import com.vertonur.bean.User;
import com.vertonur.common.OperactionCheckAction;
import com.vertonur.service.UserService;

public class LockUserAction extends OperactionCheckAction {

	@Override
	public ActionForward processRequest(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		UserAdminForm loginForm=(UserAdminForm)form;
		int[] ids = loginForm.getUserIds();
		UserService service=new UserService();
		for(int id:ids){
			User user = service.getUserById(id);
			if(user.isLocked())
				service.unLockUser(user);
			else	service.lockUser(user);
		}
		
		return mapping.findForward("AdminUserList");
	}
}

src/main/java/com/vertonur/admin/action/user/UpdateUserGroupAction.java
package com.vertonur.admin.action.user;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.vertonur.context.SystemContextService;
import com.vertonur.dms.GroupService;
import com.vertonur.dms.constant.ServiceEnum;
import com.vertonur.admin.form.UserAdminForm;
import com.vertonur.bean.User;
import com.vertonur.common.SecureHttpMethodRouterAction;
import com.vertonur.pojo.security.Group;
import com.vertonur.service.UserService;

public class UpdateUserGroupAction extends SecureHttpMethodRouterAction {

	@Override
	protected ActionForward handleGetRequest(HttpServletRequest request,
			HttpServletResponse response, ActionMapping mapping, ActionForm form)
			throws Exception {
		saveToken(request);
		GroupService groupService = SystemContextService.getService()
				.getDataManagementService(ServiceEnum.GROUP_SERVICE);
		List<Group> groups = groupService.getTopLevelGroups();
		request.setAttribute("groups", groups);

		int userId = Integer.parseInt(request.getParameter("userId"));
		UserService userService = new UserService();
		User user = userService.getUserById(userId);
		request.setAttribute("user", user);

		return mapping.findForward("UserGroupsPage");
	}

	@Override
	protected ActionForward handlePostRequest(HttpServletRequest request,
			HttpServletResponse response, ActionMapping mapping, ActionForm form)
			throws Exception {
		if (!isTokenValid(request)) {
			ActionMessages errors = new ActionMessages();
			errors.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage(
					"error.doublesubmit"));
			saveErrors(request, errors);
			return mapping.getInputForward();
		}

		UserAdminForm loginForm = (UserAdminForm) form;
		int userId = loginForm.getUserId();
		UserService userService = new UserService();
		User user = userService.getUserById(userId);

		int[] groupIds = loginForm.getGroupIds();
		GroupService groupService = SystemContextService.getService()
				.getDataManagementService(ServiceEnum.GROUP_SERVICE);

		Set<Group> groups = new HashSet<Group>();
		for (int id : groupIds) {
			Group group = groupService.getGroupById(id);
			groups.add(group);
		}
		user.setGroups(groups);
		userService.updateUser(user);

		return mapping.findForward("AdminUserList");
	}

}

src/main/java/com/vertonur/admin/action/user/UserListAction.java
package com.vertonur.admin.action.user;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vertonur.context.SystemContextService;
import com.vertonur.dms.GroupService;
import com.vertonur.dms.constant.ServiceEnum;
import com.vertonur.admin.form.UserAdminForm;
import com.vertonur.bean.User;
import com.vertonur.common.OperactionCheckAction;
import com.vertonur.pagination.PaginationContext;
import com.vertonur.pagination.PaginationContext.CxtType;
import com.vertonur.pojo.security.Group;
import com.vertonur.service.UserService;
import com.vertonur.util.ForumCommonUtil;

public class UserListAction extends OperactionCheckAction {

	@Override
	public ActionForward processRequest(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String startStr = (String) request.getParameter("start");
		int paginationStart = ForumCommonUtil
				.strToIntTransitionBuffer(startStr);

		UserAdminForm adminForm = (UserAdminForm) form;
		String username = adminForm.getUsername();
		int groupId = adminForm.getGroupId();

		long paginationSize;
		List<User> members;
		UserService userService = new UserService();
		if ((!"".equals(username) && null != username) || groupId != 0) {
			paginationSize = userService.getUserNumByNameAndGroupId_AM(
					username, groupId);
			members = userService.getUsersByNameAndGroupId_AM(username,
					paginationStart, groupId);
		} else {
			paginationSize = userService.getUserNum();
			members = userService.getUsers(paginationStart);
		}
		request.setAttribute("members", members);

		GroupService groupService = SystemContextService.getService()
				.getDataManagementService(ServiceEnum.GROUP_SERVICE);
		List<Group> groups = groupService.getTopLevelGroups();
		request.setAttribute("groups", groups);
		
		String requestPath = request.getRequestURI() + "?";
		if (!"".equals(username) && null != username) {
			requestPath += "username=" + username;
			request.setAttribute("username", username);
		}
		if (groupId != 0) {
			requestPath += "&groupId=" + groupId;
			request.setAttribute("groupId", groupId);
		}
		PaginationContext pageCxt = new PaginationContext(paginationSize,
				paginationStart, requestPath, CxtType.MEMBER);
		request.setAttribute(PaginationContext.PAGE_CXT, pageCxt);
		
		return mapping.findForward("UserListPage");
	}
}

src/main/java/com/vertonur/user/forum/action/DisplayForumsAction.java
package com.vertonur.user.forum.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vertonur.bean.Forum;
import com.vertonur.bean.Forumzone;
import com.vertonur.bean.User;
import com.vertonur.constants.Constants;
import com.vertonur.context.SystemContextService;
import com.vertonur.context.SystemContextService.SystemState;
import com.vertonur.service.ForumService;
import com.vertonur.service.ForumzoneService;
import com.vertonur.service.UserService;
import com.vertonur.session.UserSession;
import com.vertonur.util.ForumCommonUtil;
import com.vertonur.util.ForumCommonUtil.PageType;

public class DisplayForumsAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {

		// used to set taken for the login area of forum_list.jsp
		saveToken(request);
		// end

		ForumzoneService forumzoneService = new ForumzoneService();
		List<Forumzone> forumzones = forumzoneService.getForumzones();
		request.setAttribute(Constants.FORUMZONES, forumzones);

		UserService userService = new UserService();
		HttpSession session = request.getSession(false);
		UserSession userSession = (UserSession) session
				.getAttribute(Constants.USER_SESSION);
		User user = null;
		if (userSession.isLogin())
			user = userService.getUserById(userSession.getUserId());
		if (user != null) {
			ForumService forumService = new ForumService();
			for (Forumzone forumzone : forumzones) {
				List<Forum> forums = forumzone.getForums();
				for (Forum forum : forums) {
					forumService.hasNewTopicsToUser(forum, user);
				}
			}
		}

		SystemContextService service = SystemContextService.getService();
		SystemState state = service.getState();
		ForumCommonUtil.setPageSeo(request, null, null, PageType.HOME_PAGE);
		request.setAttribute("systemState", state);
		request.setAttribute("loginUserSessions", service.getLoginSessions());
		return mapping.findForward("ToForumListPage");
	}
}

src/main/java/com/vertonur/user/logout/action/LogoutAction.java
package com.vertonur.user.logout.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vertonur.context.SystemContextService;
import com.vertonur.session.UserSession;
import com.vertonur.constants.Constants;

public class LogoutAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {

		HttpSession session = request.getSession();
		UserSession userSession = (UserSession) session
				.getAttribute(Constants.USER_SESSION);
		if (userSession != null&&userSession.isLogin()) {
			SystemContextService.getService().logout(userSession);
			response.sendRedirect("user/filter_logout");
			return null;
		}
		
		return mapping.findForward("UserLoginPage");
	}
}

src/main/webapp/templates/default/user/topic/topic_list.jsp
<!-- TOPICS LISTING -->
<c:choose>
	<c:when test="${not empty pageScope.topics}">
		<c:forEach var="topic" items="${pageScope.topics}">
			<c:set var="forum" value="${topic.forum}" />
			<c:choose>
				<c:when
					test="${topic.infoType=='CATEGORY_ANNOUNCEMENT'||topic.infoType=='DEPARTMENT_ANNOUNCEMENT'||topic.infoType=='SYSTEM_ANNOUNCEMENT'}">
					<c:set var="class1" value='class="row1Announce"' />
					<c:set var="class2" value='class="row2Announce"' />
					<c:set var="class3" value='class="row3Announce"' />
				</c:when>
				<c:when test="${topic.infoType=='STICKY'}">
					<c:set var="class1" value='class="row1sticky"' />
					<c:set var="class2" value='class="row2sticky"' />
					<c:set var="class3" value='class="row3sticky"' />
				</c:when>
				<c:otherwise>
					<c:set var="class1" value='class="row1"' />
					<c:set var="class2" value='class="row2"' />
					<c:set var="class3" value='class="row3"' />
				</c:otherwise>
			</c:choose>

			<tr class="bg_small_yellow">
				<td ${class1} valign="middle" align="center" width="20"><c:choose>
						<c:when
							test="${topic.infoType=='CATEGORY_ANNOUNCEMENT'||topic.infoType=='DEPARTMENT_ANNOUNCEMENT'||topic.infoType=='SYSTEM_ANNOUNCEMENT'}">
							<img
								src="${contextPath}/templates/default/images/folder_announce.gif"
								alt="<fmt:message key="folder_descriptions.htm.announce" />" />
						</c:when>
						<c:otherwise>
							<%@ include file="topic_status_displayer.jsp"%>
						</c:otherwise>
					</c:choose></td>
				<td ${class1} width="100%"><span class="topictitle"> <a
						href="displayResponses.do?forumId=${forum.id}&topicId=${topic.id}">${topic.subject}</a>
				</span> <c:if test="${topic.newToUser}">
						<img src="${contextPath}/templates/default/images/new.gif"
							alt="New" />
					</c:if></td>

				<c:set var="statistician" value="${topic.statistician}" />
				<td ${class2} valign="middle" align="center"><span
					class="postdetails">${statistician.responseNum}</span></td>
				<td ${class3} valign="middle" align="center"><span class="name"><a
						href="displayProfile.do?userId=${topic.author.id}">${topic.author.name}</a></span>
				</td>

				<td ${class2} valign="middle" align="center"><span
					class="postdetails">${statistician.clickThroughRate}</span></td>
				<td ${class3} valign="middle" nowrap="nowrap" align="center"><span
					class="postdetails"> <c:choose>
							<c:when test="${not empty statistician.latestResponse}">
								<c:set var="latestResponse"
									value="${statistician.latestResponse}" />
								<fmt:formatDate value="${latestResponse.createdTime}"
									dateStyle="medium" />
								<fmt:formatDate value="${latestResponse.createdTime}"
									pattern="hh:mm" />
								<br />
								<a href="displayProfile.do?userId=${latestResponse.author.id}">${latestResponse.author.name}</a>
								<a
									href="displayResponses.do?forumId=${forum.id}&topicId=${latestResponse.topic.id}#${latestResponse.id}"><img
									src="${contextPath}/templates/default/images/icon_latest_reply.gif"
									border="0" alt="[Latest Reply]" /></a>
							</c:when>
							<c:otherwise>
								<fmt:message key="display_topics.jsp.noResponseYet" />
							</c:otherwise>
						</c:choose>
				</span></td>
			</tr>
		</c:forEach>
	</c:when>
	<c:otherwise>
		<c:if test="${showNoTopicTip}">
			<tr class="bg_small_yellow">
				<td ${class1} colspan="6"><span class="topictitle"> <fmt:message
							key="display_topics.jsp.noTopicYet" />
				</span></td>
			</tr>
		</c:if>
	</c:otherwise>
</c:choose>
<!-- END OF TOPICS LISTING -->

src/main/webapp/templates/default/user/topic/topic_statistic_list.jsp
<%@ include file="/templates/default/common/common_header.jsp"%>
<c:choose>
	<c:when test="${mode=='recent'}">
		<fmt:message var="title" key="header.jsp.recentTopic" />
	</c:when>
	<c:otherwise>
		<fmt:message var="title" key="header.jsp.hottestTopics" />
	</c:otherwise>
</c:choose>
<%@ include file="/templates/default/user/common/header.jsp"%>


<table cellspacing="0" cellpadding="10" width="100%" align="center"
	border="0">
	<tr>
		<td class="bodyline" valign="top">

			<table cellspacing="0" cellpadding="2" width="100%" align="center"
				border="0">
				<tr>
					<td>&nbsp;</td>
					<td valign="bottom" align="right"><c:choose>
							<c:when test="${mode=='recent'}">
								<span class="nav" style="color: #DD6900"><fmt:message
										key="recent_topics.jsp.recentTopics" /></span> &raquo;
								<a class="nav" href="displayForums.do"><fmt:message
										key="recent_topics.jsp.forums" /></a>
							</c:when>
							<c:otherwise>
								<span class="nav" style="color: #DD6900"><fmt:message
										key="header.jsp.hottestTopics" /></span> &raquo;
								<a class="nav" href="displayForums.do"><fmt:message
										key="hottest_topics.jsp.forums" /></a>
							</c:otherwise>
						</c:choose></td>
				</tr>
			</table> <c:forEach var="forum" items="${requestScope.forums}">
				<table class="forumline" cellspacing="1" cellpadding="4"
					width="100%" border="0">
					<tr>
						<th class="thcornerl" nowrap="nowrap" align="left" width="12%">&nbsp;<fmt:message
								key="recent_topics.jsp.forumName" />
						</th>
						<th class="thtop" nowrap="nowrap" align="center" colspan="2"
							height="25">&nbsp;<fmt:message
								key="recent_topics.jsp.topics" />&nbsp;
						</th>
						<th class="thtop" nowrap="nowrap" align="center" width="50">&nbsp;<fmt:message
								key="recent_topics.jsp.responses" />&nbsp;
						</th>
						<th class="thtop" nowrap="nowrap" align="center" width="100">&nbsp;<fmt:message
								key="all.jsp.author" />&nbsp;
						</th>
						<th class="thtop" nowrap="nowrap" align="center" width="50">&nbsp;<fmt:message
								key="recent_topics.jsp.views" />&nbsp;
						</th>
						<th class="thcornerr" nowrap="nowrap" align="center">&nbsp;<fmt:message
								key="recent_topics.jsp.latestResponse" />&nbsp;
						</th>
					</tr>

					<!-- TOPICS LISTING -->
					<c:choose>
						<c:when test="${mode=='recent'}">
							<c:set var="topics" value="${forum.recentTopics}" />
						</c:when>
						<c:otherwise>
							<c:set var="topics" value="${forum.hotTopics}" />
						</c:otherwise>
					</c:choose>
					<c:forEach var="topic" items="${topics}">
						<tr>
							<td class="row2" valign="middle" align="center"><a
								class="postdetails"
								href="displayTopics.do?forumzoneId=${forum.forumzone.id}&forumId=${forum.id}&forumName=${forum.name}">${forum.name}</a>&nbsp;
							</td>
							<td class="row1" valign="middle" align="center" width="20"><%@ include
									file="topic_status_displayer.jsp"%></td>
							<td class="row1" width="80%"><span class="topictitle">
									<a
									href="displayResponses.do?forumId=${forum.id}&topicId=${topic.id}">${topic.subject}</a>
							</span></td>

							<c:set var="statistician" value="${topic.statistician}" />
							<td class="row2" valign="middle" align="center"><span
								class="postdetails">${statistician.responseNum}</span></td>
							<td class="row3" valign="middle" align="center"><span
								class="name"><a
									href="displayProfile.do?userId=${topic.author.id}">${topic.author.name}</a></span>
							</td>

							<td class="row2" valign="middle" align="center"><span
								class="postdetails">${statistician.clickThroughRate}</span></td>
							<c:set var="latestResponse"
								value="${statistician.latestResponse}" />
							<td class="row3right" valign="middle" nowrap="nowrap"
								align="center"><span class="postdetails"> <c:choose>
										<c:when test="${not empty latestResponse}">
											<fmt:formatDate value="${latestResponse.createdTime}"
												dateStyle="medium" />
											<fmt:formatDate value="${latestResponse.createdTime}"
												pattern="hh:mm" />
											<br />
											<a
												href="displayProfile.do?userId=${latestResponse.author.id}">${latestResponse.author.name}</a>
											<a
												href="displayResponses.do?forumId=${forum.id}&topicId=${latestResponse.topic.id}#${latestResponse.id}"><img
												src="${contextPath}/templates/default/images/icon_latest_reply.gif"
												border="0" alt="Latest Reply" /></a>
										</c:when>
										<c:otherwise>
											<fmt:message key="recent_topics.jsp.noResponses" />
										</c:otherwise>
									</c:choose>
							</span></td>
						</tr>
					</c:forEach>
					<!-- END OF TOPICS LISTING -->
				</table>

				<table cellspacing="0" cellpadding="2" width="100%" align="center"
					border="0">
					<tr>
						<td align="left"><span class="gensmall"> <a
								class="gensmall" href="">&nbsp;</a>
						</span><span class="gensmall">&nbsp;</span></td>
					</tr>
				</table>
			</c:forEach>
		</td>
	</tr>
</table>

<%@ include file="/templates/default/common/footer.jsp"%>