src/main/java/com/vertonur/bean/Forum.java
package com.vertonur.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import com.vertonur.pojo.Category;

public class Forum {

	private Category category;
	private List<Topic> recentTopics;
	private List<Topic> hotTopics;

	public Forum() {
		category = new Category();
	}

	public Forum(Category category) {
		this.category = category;
	}

	public void addAdmins(Set<Admin> admins) {
		Iterator<Admin> iterator = admins.iterator();
		Set<com.vertonur.pojo.Admin> coreAdmins = new HashSet<com.vertonur.pojo.Admin>();
		while (iterator.hasNext()) {
			Admin admin = iterator.next();
			coreAdmins.add(admin.getCore());
		}
		category.addAdmins(coreAdmins);
	}

	public Set<Admin> getAdmins() {
		Set<com.vertonur.pojo.Admin> coreAdmins = category.getAdmins();
		Iterator<com.vertonur.pojo.Admin> iterator = coreAdmins.iterator();
		Set<Admin> admins = new HashSet<Admin>();
		while (iterator.hasNext()) {
			com.vertonur.pojo.Admin coreAdmin = iterator.next();
			Admin admin = new Admin(coreAdmin);
			admins.add(admin);
		}
		return admins;
	}

	public Category getCore() {
		return category;
	}

	public String getDescription() {
		return category.getDescription();
	}

	public Forumzone getForumzone() {
		return new Forumzone(category.getDepartment());
	}

	public int getId() {
		return category.getId();
	}

	public String getName() {
		return category.getName();
	}

	public ForumStatistician getStatistician() {
		return new ForumStatistician(category.getStatistician());
	}

	public boolean isHasNewTopic() {
		return category.isHasNewInfo();
	}

	public void removeAdmins() {
		category.removeAdmins();
	}

	public void setCreatedTime(Date date) {
		category.setCreatedTime(date);
	}

	public void setCreator(Admin admin) {
		category.setCreator(admin.getCore());
	}

	public void setDescription(String description) {
		category.setDescription(description);
	}

	public void setName(String name) {
		category.setName(name);
	}

	public void setStatistician(ForumStatistician forumStatistician) {
		category.setStatistician(forumStatistician.getCore());
	}

	public boolean isModerated() {
		return category.isModerated();
	}

	public void setModerated(boolean moderated) {
		category.setModerated(moderated);
	}

	public boolean isDeprecated() {
		return category.isDeprecated();
	}

	public void setDeprecated(boolean deprecated) {
		category.setDeprecated(deprecated);
	}

	public List<Topic> getRecentTopics() {
		return recentTopics;
	}

	public void setRecentTopics(List<Topic> recentTopics) {
		this.recentTopics = recentTopics;
	}

	public List<Topic> getHotTopics() {
		return hotTopics;
	}

	public void setHotTopics(List<Topic> hotTopics) {
		this.hotTopics = hotTopics;
	}

	public int getPriority() {
		return category.getPriority();
	}

	public void setPriority(int priority) {
		category.setPriority(priority);
	}
}

src/main/java/com/vertonur/bean/Info.java
package com.vertonur.bean;

import java.util.Date;
import java.util.List;

import com.vertonur.pojo.AbstractInfo;
import com.vertonur.pojo.Attachment;
import com.vertonur.pojo.State;

public abstract class Info {

	public List<Attachment> getAttachments() {
		return getCore().getAttachments();
	}

	public User getAuthor() {
		return new User(getCore().getAuthor());
	}

	public String getContent() {
		return getCore().getContent();
	}

	public abstract AbstractInfo getCore();

	public Date getCreatedTime() {
		return getCore().getCreatedTime();
	}

	public int getId() {
		return getCore().getId();
	}

	public String getSubject() {
		return getCore().getSubject();
	}

	public void setAuthor(User theCurrentUser) {
		getCore().setAuthor(theCurrentUser.getCore());
	}

	public void setContent(String content) {
		getCore().setContent(content);
	}

	public void setCreatedTime(Date date) {
		getCore().setCreatedTime(date);
	}

	public void setSubject(String title) {
		getCore().setSubject(title);
	}

	public State getState() {
		return getCore().getState();
	}

	public void setState(State state) {
		getCore().setState(state);
	}
}

src/main/java/com/vertonur/admin/action/AdminIndexAction.java
package com.vertonur.admin.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vertonur.common.OperactionCheckAction;
import com.vertonur.util.PermissionUtils;

public class AdminIndexAction extends OperactionCheckAction {

	@Override
	public ActionForward processRequest(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		request.setAttribute("servicePath", "admin/statistic");

		HttpSession session = request.getSession();
		session.setAttribute("enableOperateGroup", PermissionUtils
				.checkOperateGroupPermission(getServlet().getServletContext()));
		session.setAttribute("enableOperateUser", PermissionUtils
				.checkOperateUserPermission(getServlet().getServletContext()));
		session.setAttribute("enableOperateForumzone", PermissionUtils
				.checkOperateForumzonePermission(getServlet()
						.getServletContext()));
		session.setAttribute("enableOperateForum", PermissionUtils
				.checkOperateForumPermission(getServlet().getServletContext()));
		session.setAttribute("enableConfigRuntimeParameter", PermissionUtils
				.checkConfigRuntimeParameterPermission(getServlet()
						.getServletContext()));
		session.setAttribute("enableOperateRanking",
				PermissionUtils.checkOperateRankingPermission(getServlet()
						.getServletContext()));
		session.setAttribute("enableConfigPoints", PermissionUtils
				.checkConfigPointsPermission(getServlet().getServletContext()));
		session.setAttribute("enableConfigBackendPermission", PermissionUtils
				.checkConfigPointsPermission(getServlet().getServletContext()));
		return mapping.findForward("AdminIndex");
	}
}

src/main/java/com/vertonur/admin/action/ForumzoneListAction.java
package com.vertonur.admin.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vertonur.bean.Forumzone;
import com.vertonur.common.OperactionCheckAction;
import com.vertonur.constants.Constants;
import com.vertonur.service.ForumzoneService;

public class ForumzoneListAction extends OperactionCheckAction {

	@Override
	public ActionForward processRequest(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		saveToken(request);
		ForumzoneService forumzoneService = new ForumzoneService();
		List<Forumzone> forumzones = forumzoneService.getForumzones();
		request.setAttribute(Constants.FORUMZONES, forumzones);
		return mapping.findForward("ForumzoneListPage");
	}

}

src/main/java/com/vertonur/admin/action/GroupListAction.java
package com.vertonur.admin.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vertonur.bean.User;
import com.vertonur.common.OperactionCheckAction;
import com.vertonur.context.SystemContextService;
import com.vertonur.dms.GroupService;
import com.vertonur.dms.constant.ServiceEnum;
import com.vertonur.pojo.security.Group;
import com.vertonur.service.UserService;

public class GroupListAction extends OperactionCheckAction {

	@Override
	public ActionForward processRequest(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {

		GroupService groupService = SystemContextService.getService()
				.getDataManagementService(ServiceEnum.GROUP_SERVICE);
		String action = request.getParameter("action");
		if ("edit".equals(action) || "add".equals(action)) {
			saveToken(request);

			List<Group> groups = groupService.getTopLevelGroups();
			request.setAttribute("groups", groups);

			String groupIdStr = request.getParameter("groupId");
			if (groupIdStr != null && !"".equals(groupIdStr)) {
				int groupId = Integer.parseInt(groupIdStr);
				Group group = groupService.getGroupById(groupId);
				if (group.getNestedLevel() == 0)
					groups.remove(group);

				request.setAttribute("edittedGroup", group);
			}

			return mapping.findForward("GroupEditPage");
		} else if ("subGroup".equals(action)) {
			int groupId = Integer.parseInt(request.getParameter("groupId"));
			Group group = groupService.getGroupById(groupId);
			request.setAttribute("group", group);

			String type = request.getParameter("type");
			if (type != null && "list".equals(type))
				return mapping.findForward("SubGroupListPage");
			else if (type != null && "rankingOption".equals(type)) {
				return mapping.findForward("RankingSubGroupOptionPage");
			} else if (type != null && "userOption".equals(type)) {
				int userId = Integer.parseInt(request.getParameter("userId"));
				UserService userService = new UserService();
				User user = userService.getUserById(userId);
				request.setAttribute("user", user);
				return mapping.findForward("UserSubGroupOptionPage");
			} else
				return mapping.findForward("SubGroupOptionPage");
		} else {
			saveToken(request);

			String permissionConfig = request.getParameter("permissionConfig");
			List<Group> groups = null;
			if ("true".equals(permissionConfig))
				groups = groupService.getAdminTopLevelGroups();
			else
				groups = groupService.getTopLevelGroups();
			request.setAttribute("groups", groups);
			return mapping.findForward("GroupListPage");
		}
	}
}

src/main/java/com/vertonur/admin/action/user/UserListAction.java
package com.vertonur.admin.action.user;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vertonur.context.SystemContextService;
import com.vertonur.dms.GroupService;
import com.vertonur.dms.constant.ServiceEnum;
import com.vertonur.admin.form.UserAdminForm;
import com.vertonur.bean.User;
import com.vertonur.common.OperactionCheckAction;
import com.vertonur.pagination.PaginationContext;
import com.vertonur.pagination.PaginationContext.CxtType;
import com.vertonur.pojo.security.Group;
import com.vertonur.service.UserService;
import com.vertonur.util.ForumCommonUtil;

public class UserListAction extends OperactionCheckAction {

	@Override
	public ActionForward processRequest(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String startStr = (String) request.getParameter("start");
		int paginationStart = ForumCommonUtil
				.strToIntTransitionBuffer(startStr);

		UserAdminForm adminForm = (UserAdminForm) form;
		String username = adminForm.getUsername();
		int groupId = adminForm.getGroupId();

		long paginationSize;
		List<User> members;
		UserService userService = new UserService();
		if ((!"".equals(username) && null != username) || groupId != 0) {
			paginationSize = userService.getUserNumByNameAndGroupId_AM(
					username, groupId);
			members = userService.getUsersByNameAndGroupId_AM(username,
					paginationStart, groupId);
		} else {
			paginationSize = userService.getUserNum();
			members = userService.getUsers(paginationStart);
		}
		request.setAttribute("members", members);

		GroupService groupService = SystemContextService.getService()
				.getDataManagementService(ServiceEnum.GROUP_SERVICE);
		List<Group> groups = groupService.getTopLevelGroups();
		request.setAttribute("groups", groups);
		
		String requestPath = request.getRequestURI() + "?";
		if (!"".equals(username) && null != username) {
			requestPath += "username=" + username;
			request.setAttribute("username", username);
		}
		if (groupId != 0) {
			requestPath += "&groupId=" + groupId;
			request.setAttribute("groupId", groupId);
		}
		PaginationContext pageCxt = new PaginationContext(paginationSize,
				paginationStart, requestPath, CxtType.MEMBER);
		request.setAttribute(PaginationContext.PAGE_CXT, pageCxt);
		
		return mapping.findForward("UserListPage");
	}
}

src/main/java/com/vertonur/admin/forum/action/CreateForumAction.java
package com.vertonur.admin.forum.action;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.vertonur.admin.forum.form.ForumForm;
import com.vertonur.bean.Admin;
import com.vertonur.bean.Forum;
import com.vertonur.bean.ForumStatistician;
import com.vertonur.constants.Constants;
import com.vertonur.service.ForumService;
import com.vertonur.service.UserService;
import com.vertonur.session.UserSession;

public final class CreateForumAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if (!isTokenValid(request)) {
			ActionMessages errors = new ActionMessages();
			errors.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage(
					"error.doublesubmit"));
			saveErrors(request, errors);
			return mapping.getInputForward();
		}

		ForumForm castedForm = (ForumForm) form;
		String forumName = castedForm.getForumName();
		String forumDescription = castedForm.getForumDescription();
		boolean moderated = castedForm.isModerated();
		int priority = castedForm.getPriority();

		Forum forum = new Forum();
		forum.setName(forumName);
		forum.setDescription(forumDescription);
		forum.setCreatedTime(new Date());
		forum.setModerated(moderated);
		forum.setStatistician(new ForumStatistician());
		forum.setPriority(priority);

		HttpSession session = request.getSession(false);
		UserSession userSession = (UserSession) session
				.getAttribute(Constants.USER_SESSION);
		UserService service = new UserService();
		Admin admin = (Admin) service.getUserById(userSession.getUserId());
		forum.setCreator(admin);

		ForumService forumService = new ForumService();
		int forumzoneId = castedForm.getNewForumzoneId();
		if (forumService.saveForum(forumzoneId, forum) != null) {
			resetToken(request);
			ActionMessages messages = new ActionMessages();
			messages.add(
					ActionMessages.GLOBAL_MESSAGE,
					new ActionMessage(
							"message.admin.forum.action.CreateForumAction.create.succeed"));
			saveMessages(request, messages);
			return mapping.findForward("ForumList");
		} else {
			ActionMessages errors = new ActionMessages();
			errors.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage(
					"error.admin.forum.action.CreateForumAction.create.failed"));
			saveErrors(request, errors);
			return mapping.getInputForward();
		}
	}
}

src/main/java/com/vertonur/admin/forum/action/DeleteForumAction.java
package com.vertonur.admin.forum.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.vertonur.admin.forum.form.ForumForm;
import com.vertonur.bean.Forum;
import com.vertonur.common.OperactionCheckAction;
import com.vertonur.dms.exception.CategoryModerationListNotEmptyException;
import com.vertonur.service.ForumService;

public final class DeleteForumAction extends OperactionCheckAction {

	@Override
	public ActionForward processRequest(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		resetToken(request);
		ForumForm castedForm = (ForumForm) form;
		String[] forumIds = castedForm.getForumIds();

		ForumService forumService = new ForumService();
		for (String forumIdStr : forumIds) {
			String[] tmp = forumIdStr.split("_");
			Forum forum = forumService.getForumById(Integer.parseInt(tmp[0]),
					Integer.parseInt(tmp[1]),false);
			forum.setDeprecated(true);
			try {
				forumService.updateForum(forum);
			} catch (CategoryModerationListNotEmptyException e) {
				ActionMessages errors = new ActionMessages();
				errors.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage(
						"msg.pending.to.modernate"));
				saveErrors(request, errors);
				return mapping.findForward("ForumList");
			}
		}

		ActionMessages messages = new ActionMessages();
		messages.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage(
				"message.admin.forum.action.DeleteForumAction.delete.succeed"));
		saveMessages(request, messages);
		return mapping.findForward("ForumList");
	}
}

src/main/webapp/templates/default/admin/forum_form.jsp
<%@ include file="/templates/default/common/common_header.jsp"%>
<link rel="stylesheet" type="text/css"
	href="${contextPath}/templates/default/styles/style.css" />

<c:choose>
	<c:when test="${not empty requestScope.ForumForm.forumName}">
		<c:set var="forumId" value="${requestScope.ForumForm.forumId}" />
		<c:set var="forumzoneId"
			value="${requestScope.ForumForm.forumzoneId}" />
		<c:set var="newForumzoneId"
			value="${requestScope.ForumForm.newForumzoneId}" />
		<c:set var="forumName" value="${requestScope.ForumForm.forumName}" />
		<c:set var="forumDescription"
			value="${requestScope.ForumForm.forumDescription}" />
		<c:set var="moderated" value="${requestScope.ForumForm.moderated}" />
		<c:set var="priority" value="${requestScope.ForumForm.priority}" />
	</c:when>
	<c:when test="${not empty requestScope.forum}">
		<c:set var="forumName" value="${requestScope.forum.name}" />
		<c:set var="forumDescription"
			value="${requestScope.forum.description}" />
		<c:set var="moderated" value="${requestScope.forum.moderated}" />
		<c:set var="forumId" value="${requestScope.forum.id}" />
		<c:set var="forumzoneId" value="${requestScope.forum.forumzone.id}" />
		<c:set var="newForumzoneId" value="${requestScope.forum.forumzone.id}" />
		<c:set var="priority" value="${requestScope.forum.priority}" />
	</c:when>
</c:choose>

<html:form action="${servicePath}" method="post"
	enctype="multipart/form-data">
	<html:errors />
	<input type="hidden" name="forumId" value="${forumId}" />
	<input type="hidden" name="forumzoneId" value="${forumzoneId}" />
	<table class="forumline" cellspacing="1" cellpadding="3" width="100%"
		border="0">
		<tr>
			<th class="thhead" valign="middle" colspan="2" height="25"><fmt:message
					key="forum_form.jsp.title" /></th>
		</tr>

		<tr>
			<td class="row1" width="20%"><span class="gen"><fmt:message
						key="forum_form.jsp.forum.name" /></span></td>
			<td class="row2"><input type="text" class="post"
				style="WIDTH: 200px" maxlength="200" size="25" name="forumName"
				value="${forumName}" /> <html:errors property="forumName" /></td>
		</tr>

		<tr>
			<td class="row1" width="38%"><span class="gen"><fmt:message
						key="forum_form.jsp.priority" /></span></td>
			<td class="row2"><input type="text" class="post"
				style="WIDTH: 200px" maxlength="150" size="25" name="priority"
				value="${priority}" /> <html:errors property="priority" /></td>
		</tr>

		<tr>
			<td class="row1" width="38%"><span class="gen"><fmt:message
						key="forum_form.jsp.moderate" /></span></td>
			<td class="row2"><span class="gensmall"> <input
					class="post" type="radio" name="moderated" value="0"
					<c:if test="${!moderated}">checked</c:if> />&nbsp;<fmt:message
						key="forum_form.jsp.no" />&nbsp;&nbsp; <input class="post"
					type="radio" name="moderated" value="1"
					<c:if test="${moderated}">checked</c:if> />&nbsp;<fmt:message
						key="forum_form.jsp.yes" />
			</span></td>
		</tr>

		<tr>
			<td class="row1"><span class="gen"><fmt:message
						key="forum_form.jsp.forumzone" /></span></td>
			<td class="row2"><select name="newForumzoneId">
					<c:forEach var="forumzone" items="${requestScope.allForumzones}">
						<option value="${forumzone.id}"
							<c:if test="${newForumzoneId==forumzone.id}">selected</c:if>>${forumzone.name}</option>
					</c:forEach>
			</select></td>
		</tr>

		<tr>
			<td class="row1"><span class="gen"><fmt:message
						key="forum_form.jsp.desc" /></span></td>
			<td class="row2"><textarea name="forumDescription" cols="40"
					rows="10" class="post" style="width: 100%">${forumDescription}</textarea>
				<html:errors property="forumDescription" /></td>
		</tr>

		<tr align="center">
			<td class="catbottom" colspan="2" height="28"><input
				class="mainoption" type="submit"
				value="<fmt:message key="forum_form.jsp.update" />" name="submit" /></td>
		</tr>

	</table>
</html:form>

src/main/webapp/templates/default/admin/moderation_list_posts.jsp
<%@ include file="/templates/default/common/common_header.jsp"%>
<link rel="stylesheet" type="text/css"
	href="${contextPath}/templates/default/styles/style.css" />



<table border="0" cellpadding="3" cellspacing="1" width="100%"
	class="forumline">
	<tr>
		<th class="thhead" align="center" height="28"><fmt:message
				key="moderation_list_posts.jsp.pending.msgs" />
		</td>
	</tr>

	<c:choose>
		<c:when test="${empty logs}">
			<tr>
				<td align="center"><span class="gensmall"><fmt:message
							key="moderation_list_posts.jsp.none.to.moderate" /></span></td>
			</tr>
		</c:when>
		<c:otherwise>
			<c:if test="${not empty logs}">
				<html:form action="admin/moderation/update" method="post">
					<tr>
						<td class="nav" nowrap="nowrap" align="right"><%@ include
								file="/templates/common/pagination/pagination.jsp"%>
						</td>
					</tr>
					
					<c:forEach var="log" items="${logs}">
						<c:set var="logType" value="${log.logType}" />
						<c:set var="modifiedInfo" value="${log.modifiedInfo}" />
						<c:choose>
							<c:when test="${logType=='INFO'}">
								<c:set var="topicSubject" value="${modifiedInfo.subject}" />
							</c:when>
							<c:otherwise>
								<c:set var="topicSubject" value="${modifiedInfo.info.subject}" />
							</c:otherwise>
						</c:choose>
						<c:set var="msgId" value="${modifiedInfo.id}" />
						<c:set var="logId" value="${log.id}" />

						<tr>
							<td class="row1">
								<table width="100%" align="center" cellpadding="0"
									cellspacing="1">
									<tr>
										<td colspan="2" class="catleft">&nbsp;<span class="gen"><b>${topicSubject}</b></span></td>
									</tr>

									<tr>
										<td>
											<table width="95%" align="center">

												<tr>
													<th class="thcornerl" width="150" height="26"><fmt:message
															key="moderation_list_posts.jsp.author" /></th>
													<th class="thcornerr"><fmt:message
															key="moderation_list_posts.jsp.msg.title" /></th>
												</tr>

												<tr>
													<td align="left" valign="top" class="row1"><span
														class="name"><a name=""></a><b>${modifiedInfo.author.name}</b></span></td>

													<td class="row1" height="28" valign="top">
														<table width="100%" border="0" cellspacing="0"
															cellpadding="0">
															<tr>
																<td width="100%"><span class="gensmall"><fmt:message
																			key="moderation_list_posts.jsp.subject" />:
																		${modifiedInfo.subject} </span></td>
															</tr>
															<tr>
																<td colspan="2"><hr /></td>
															</tr>
															<tr>
																<td colspan="2"><span class="postbody">${modifiedInfo.content}</span>
																</td>
															</tr>
														</table>
													</td>
												</tr>

												<tr>
													<td colspan="2" align="right"><span class="gensmall">
															<input type="radio" name="updateOpt_${msgId}"
															value="${requestScope.approved}"> <fmt:message
																key="moderation_list_posts.jsp.aprove" />&nbsp; <input
															type="radio" name="updateOpt_${msgId}"
															value="${requestScope.deferred}" checked> <fmt:message
																key="moderation_list_posts.jsp.defer" />&nbsp; <input
															type="radio" name="updateOpt_${msgId}"
															value="${requestScope.rejected}"> <fmt:message
																key="moderation_list_posts.jsp.reject" />&nbsp; <input
															type="hidden" name="msgIds" value="${msgId}"> <input
															type="hidden" name="logTypes" value="${logType}">
															<input type="hidden" name="logIds" value="${logId}">
													</span></td>
												</tr>

												<tr>
													<td colspan="2" height="1" class="spacerow"><img
														src="${contextPath}/templates/default/images/spacer.gif"
														alt="" width="1" height="1" /></td>
												</tr>
											</table>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</c:forEach>

					<tr>
						<td class="nav" nowrap="nowrap" align="right"><%@ include
								file="/templates/common/pagination/pagination.jsp"%>
						</td>
					</tr>
					<tr>
						<td align="center" class="catleft"><input type="hidden"
							name="msgType" value="topic"><input class="mainoption"
							type="submit"
							value="<fmt:message key="moderation_list_posts.jsp.submit" />"></td>
					</tr>
				</html:form>
			</c:if>
		</c:otherwise>
	</c:choose>
</table>

src/main/webapp/templates/default/admin/sub_group_list.jsp
<%@ include file="/templates/default/common/common_header.jsp"%>

<c:forEach var="group" items="${group.subGroups}">
	<tr bgcolor="#f4f4f4">
		<c:choose>
			<c:when test="${permissionConfig}">
				<c:if test="${group.groupType=='GENERIC_ADMIN'}">
					<td colspan="${colspan}"><span class="gen"><c:forEach
								begin="0" end="${group.nestedLevel}">&nbsp;&nbsp;</c:forEach>
							${group.name} </span></td>
				</c:if>
			</c:when>
			<c:otherwise>
				<td colspan="${colspan}"><span class="gen"><c:forEach
							begin="0" end="${group.nestedLevel}">&nbsp;&nbsp;</c:forEach>
						${group.name} </span></td>
			</c:otherwise>
		</c:choose>

		<c:if test="${!permissionConfig}">
			<td align="center"><span class="gen"><a
					href="${contextPath}/do/admin/group/get?action=edit&&groupId=${group.id}"><fmt:message
							key="group_list.jsp.edit" /></a></span></td>
			<td align="center"><c:if test="${group.deletable}">
					<input type="checkbox" name="groupIds" value="${group.id}" />
				</c:if></td>
		</c:if>

		<c:choose>
			<c:when test="${permissionConfig}">
				<c:if test="${group.groupType=='GENERIC_ADMIN'}">
					<td class="row2" align="center"><span class="gen"><a
							href="${contextPath}/do/admin/permission/list?groupId=${group.id}"><fmt:message
									key="group_list.jsp.security" /></a></span></td>
				</c:if>
			</c:when>
			<c:otherwise>
				<td class="row2" align="center"><span class="gen"><a
						href="${contextPath}/do/admin/permission/list?groupId=${group.id}"><fmt:message
								key="group_list.jsp.security" /></a></span></td>
			</c:otherwise>
		</c:choose>

	</tr>

	<c:import
		url="/do/admin/group/get?action=subGroup&&groupId=${group.id}" />
</c:forEach>